### PR TITLE
Rcpp

### PR DESCRIPTION
**Pull request by mihem**
Hi Anna,
dirMulSample and the "mapply" function turned out to be a bottleneck. For a relatively small snRNAseq dataset (one sample in my case) with 30044 rows (genes) and 20251 columns(cells) it took 368s on my machine. I therefore wrote Rcpp functions for dirMulSample and mapply iteration.
My Rcpp implementation, which only uses Rcpp (no Armadillo or Eigen), was approximately 10x faster (38s) on my machine. 

Note: I also removed the argument "epsilon" since I think it's determined by folds and removing it simplifies the function.

Please verify that results are the sample and feel free to edit.

Best,
Mischko

### CODE REVIEW

**Comment by mihem** [comment]
This is a short sanity check that the Rcpp version (which I call with countsplit because it's the one I have installed locally already) and mycountsplit (which represents your original version) returns the same result:

```
sset.seed(1)
n <- 300
p <- 500
my_X <- matrix(rnbinom(n*p, mu=5, size=3), nrow=n)
my_X <- as(my_X, "dgCMatrix")

set.seed(1)
my_overdisps <- rnorm(p, 1, 0.1)
my_folds <- 10

set.seed(1)
r1 <- mycountsplit(X = my_X, folds = my_folds, overdisps = my_overdisps)

set.seed(1)
r2 <- countsplit(X = my_X, folds = my_folds, overdisps = my_overdisps)

identical(r1, r2)
```

and a benchmark

```

countsplit_orig_seed <- function() {
  set.seed(1)
  mycountsplit(X = my_X, folds = my_folds, overdisps = my_overdisps)
}

countsplit_rcpp_seed <- function() {
  set.seed(1)
  countsplit(X = my_X, folds = my_folds, overdisps = my_overdisps)
}

bench::mark(
  orig = countsplit_orig_seed(),
  rcpp = countsplit_rcpp_seed()
)
```

"only" ~6x speed increase, but i think this increases with larger matrices.
```
+ # A tibble: 2 × 13
  expression      min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc
  <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>
1 orig          1.42s    1.42s     0.705   743.1MB     4.23     1     6
2 rcpp       211.41ms    221ms     4.59     36.9MB     3.06     3     2
```

**Comment by mihem** [comment]
Sorry, this looked like an easy change, but it's not!

In your R version epsilon is a vector with length folds. and you use epislon *b as the shape parameter in rgamma. This works because in R rgamma can be a vector of shapes, but in Rcpp::rgamma shape needs to be a double. 

What you can do is call the R rgamma function inside Rcpp using:

```
  Rcpp::Function rgamma("rgamma");  // Create an Rcpp::Function object for rgamma
```
but this is then slower then the R rgamma function. You could also just use your R dirMulSample function and use Rcpp for the mapply loop.

````
    int n = x.size();
    Rcpp::IntegerMatrix result(folds, n);
    Rcpp::IntegerMatrix sample(folds, 1);

    for (int i = 0; i < n; i++) {
      Rcpp::Function dirMulSample("dirMulSample");
      sample = dirMulSample(x[i], folds, overdisps[i], epsilons);
      for (int j = 0; j < folds; j++) {
        result(j, i) = sample(j, 0);
      }
```

But i benchmarked this and this was only 1.5 x faster than the R version. So i think best way is still to use the fast Rcpp version. If you think epsilon is super important maybe use R version for custom epsilon and Rcpp for the other cases.
I think the end user will use epsilon as you recommend and will care more about speed.

**Comment by anna-neufeld** [comment]
Thank you!! I think that using epsilon not equal to 1/folds only comes up when folds=2. And in the folds=2 case, we don't need to do multinomial sampling so the code is faster anyway. I'll plan to make a wrapper where your fast version is usually called, but where in some cases a slower version with user-picked epsilon can be called.

**Comment by mihem** [comment]
This pull request has been integrated by @anna-neufeld manually.

**Comment by anna-neufeld** [comment]
Thank you! Sorry for integrating manually- I was fixing the Poisson bug and am not super good at using branches/forks/etc. yet so I just pushed it separately.

**Comment by mihem** [comment]
No problem. I am no expert either, but github makes it usually super easy to integrate changes (and so many pages that help you with that) . And you could also first revise my pull request or tell me to revise it, before you merge it. Additionally, you could create a dev branch, where you do some testing and only merge them with your main branch after some testing.

**Pull request closed without merging**
